package cn.novelmaker.wg1337.ui.theme

import androidx.compose.ui.graphics.Color

// ─── Light Theme Colors (淡色 #515B92 / #DEE0FF) ───
val md_theme_light_primary = Color(0xFF515B92)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDEE0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF0A1545)
val md_theme_light_secondary = Color(0xFF5B5D72)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0E2F9)
val md_theme_light_onSecondaryContainer = Color(0xFF181B2C)
val md_theme_light_tertiary = Color(0xFF5A6B9B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1B21)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1B21)
val md_theme_light_surfaceVariant = Color(0xFFE2E2F0)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_surfaceContainerHighest = Color(0xFFDEDEEB)
val md_theme_light_outline = Color(0xFF757682)
val md_theme_light_outlineVariant = Color(0xFFC6C6D4)

// ─── Dark Theme Colors (深色统一蓝紫系) ───
val md_theme_dark_primary = Color(0xFFBCC2FF)
val md_theme_dark_onPrimary = Color(0xFF1A2360)
val md_theme_dark_primaryContainer = Color(0xFF3A4378)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_secondary = Color(0xFFC8C7DF)
val md_theme_dark_onSecondary = Color(0xFF2B2E3A)
val md_theme_dark_secondaryContainer = Color(0xFF41435A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4E2F7)
val md_theme_dark_tertiary = Color(0xFFB6C7FF)
val md_theme_dark_onTertiary = Color(0xFF2A3550)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF131318)
val md_theme_dark_onBackground = Color(0xFFE3E2E9)
val md_theme_dark_surface = Color(0xFF131318)
val md_theme_dark_onSurface = Color(0xFFE3E2E9)
val md_theme_dark_surfaceVariant = Color(0xFF45454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2D2E36)
val md_theme_dark_outline = Color(0xFF8F909C)
val md_theme_dark_outlineVariant = Color(0xFF45454F)
