package cn.novelmaker.wg1337.ui.theme

import androidx.compose.ui.graphics.Color

// ─── Light Theme Colors (紫红色 #7B3E6F) ───
val md_theme_light_primary = Color(0xFF7B3E6F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8F0)
val md_theme_light_onPrimaryContainer = Color(0xFF320131)
val md_theme_light_secondary = Color(0xFF6E5671)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF8D8F5)
val md_theme_light_onSecondaryContainer = Color(0xFF27142B)
val md_theme_light_tertiary = Color(0xFF6E5671)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0E9)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_surfaceContainerHighest = Color(0xFFE6E0E5)
val md_theme_light_outline = Color(0xFF7B7280)
val md_theme_light_outlineVariant = Color(0xFFCEC0CE)

// ─── Dark Theme Colors ───
val md_theme_dark_primary = Color(0xFFE7B8DA)
val md_theme_dark_onPrimary = Color(0xFF4B1447)
val md_theme_dark_primaryContainer = Color(0xFF632D5E)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8F0)
val md_theme_dark_secondary = Color(0xFFDABDDD)
val md_theme_dark_onSecondary = Color(0xFF3D2841)
val md_theme_dark_secondaryContainer = Color(0xFF544058)
val md_theme_dark_onSecondaryContainer = Color(0xFFF8D8F5)
val md_theme_dark_tertiary = Color(0xFFDABDDD)
val md_theme_dark_onTertiary = Color(0xFF3D2841)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC3CE)
val md_theme_dark_surfaceContainerHighest = Color(0xFF332F36)
val md_theme_dark_outline = Color(0xFF968C99)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
